
import type { Contract } from './types';

export const initialContractData: Contract[] = [
    {
        id: "split-sheet-acuerdo-de-coautoria",
        title: "Split Sheet: Acuerdo de Coautoría",
        tags: "música, colaboración, bilingüe",
        category: "música, colaboración",
        type: "Plantilla",
        status: "Borrador",
        mins: "5",
        filetypes: "PDF, DOCX",
        verified: true,
        image: "https://placehold.co/400x225.png",
        desc: "Define porcentajes de autoría y administración de forma clara. Incluye cláusulas de créditos y regalías.",
        shortDesc: "Ideal para sesiones. Establece porcentajes, administración y créditos en minutos.",
    },
    {
        id: "licencia-de-uso-de-obra-sincronizacion",
        title: "Licencia de Uso de Obra: Sincronización",
        tags: "licencias, sincronización, pro, bilingüe",
        category: "licencias",
        type: "Contrato",
        status: "Completado",
        mins: "7",
        filetypes: "PDF, DOCX",
        verified: true,
        image: "https://placehold.co/400x225.png",
        desc: "Autoriza el uso audiovisual de una obra musical en películas, anuncios o series. Incluye campos de territorio, plazo y medios.",
        shortDesc: "Cubre medios, exclusividad y reportes. Pensado para productoras, sellos y creadores.",
    },
    {
        id: "contrato-de-artista-en-vivo",
        title: "Contrato de Artista en Vivo",
        tags: "eventos, performance, artista",
        category: "eventos",
        type: "Contrato",
        status: "Pendiente",
        mins: "6",
        filetypes: "PDF, DOCX",
        verified: true,
        image: "https://firebasestorage.googleapis.com/v0/b/new-prototype-rmkd6.firebasestorage.app/o/jean1.png?alt=media&token=b54755a8-0876-4daf-ab49-9dfb3857eeb7",
        desc: "Asegura logística, pagos, backline y cancelaciones para presentaciones en vivo. Incluye riders y penalizaciones.",
        shortDesc: "Protege a artista y contratante. Claridad en pagos, horarios y condiciones técnicas.",
    },
    {
        id: "acuerdo-de-distribucion-digital",
        title: "Acuerdo de Distribución Digital",
        tags: "distribución, plataformas, regalías, pro",
        category: "distribución",
        type: "Contrato",
        status: "Borrador",
        mins: "8",
        filetypes: "PDF, DOCX",
        verified: true,
        image: "https://placehold.co/400x225.png",
        desc: "Estructura comisiones, territorios, ventanas de lanzamiento y reportes con agregadores o sellos.",
        shortDesc: "Define split de regalías, auditorías y derechos de catálogo para releases.",
    },
    {
        id: "contrato-de-manager-de-artista",
        title: "Contrato de Manager de Artista",
        tags: "management, comisión, representación, pro",
        category: "management",
        type: "Contrato",
        status: "Completado",
        mins: "10",
        filetypes: "PDF, DOCX",
        verified: true,
        image: "https://placehold.co/400x225.png",
        desc: "Define alcance de representación, comisiones, exclusividad y terminación con managers o agencias.",
        shortDesc: "Incluye nivel de comisión por áreas, sunset clause y gastos reembolsables.",
    },
    {
        id: "contrato-de-produccion-musical",
        title: "Contrato de Producción Musical",
        tags: "música, producción, obra por encargo",
        category: "música",
        type: "Contrato",
        status: "Borrador",
        mins: "9",
        filetypes: "PDF, DOCX",
        verified: true,
        image: "https://placehold.co/400x225.png",
        desc: "Alinea entregables, propiedad intelectual y pagos por hitos con productores y artistas.",
        shortDesc: "Incluye obra por encargo, stems, revisiones y créditos de productor.",
    },
    {
        id: "cesion-de-derechos-publishing",
        title: "Cesión de Derechos (Publishing)",
        tags: "publishing, licencias, edición, pro",
        category: "licencias",
        type: "Contrato",
        status: "Pendiente",
        mins: "11",
        filetypes: "PDF, DOCX",
        verified: true,
        image: "https://firebasestorage.googleapis.com/v0/b/new-prototype-rmkd6.firebasestorage.app/o/img6.jpg?alt=media&token=8d5c0dd4-dc3d-4d48-871d-66e738b7b32b",
        desc: "Formaliza la cesión total o parcial de derechos editoriales con cláusulas de reversion y reportes.",
        shortDesc: "Modelo para works for hire, participación y subedición con límites claros.",
    },
    {
        id: "acuerdo-de-colaboracion-entre-artistas",
        title: "Acuerdo de Colaboración entre Artistas",
        tags: "colaboración, música, derechos",
        category: "colaboración",
        type: "Plantilla",
        status: "Completado",
        mins: "4",
        filetypes: "PDF, DOCX",
        verified: true,
        image: "https://placehold.co/400x225.png",
        desc: "Define aportes creativos, splits de master y publishing, y autorizaciones de lanzamiento.",
        shortDesc: "Perfecto para feats. Cubre créditos, distribución de ingresos y aprobación creativa.",
    },
];
